CREATE INDEX IDX_DEV_NOTICE_VALUEID ON DEV_NOTICE(#ISSUE_ID#,#START_TIME#,#END_TIME#,#EDIT_TIME#)
CREATE INDEX IDX_DEV_USER_NOTICE_USERID ON DEV_USER_NOTICE(#USER_ID#,#NOTICE_ID#,#READ_TIME#)
CREATE INDEX IDX_DEV_ROLE_CATALOG_ROLEID ON DEV_ROLE_CATALOG(#ROLE_ID#,#CATALOG_ID#)